/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VerificationRequestId = IDL.Nat;
export const WithdrawalRequestId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BitcoinAmount = IDL.Nat;
export const SegwitMetadata = IDL.Record({ 'p2wpkhStatus' : IDL.Bool });
export const BitcoinWallet = IDL.Record({
  'publicKey' : IDL.Vec(IDL.Nat8),
  'address' : IDL.Text,
  'segwitMetadata' : SegwitMetadata,
});
export const UserProfile = IDL.Record({
  'bitcoinWallet' : IDL.Opt(BitcoinWallet),
  'name' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'instantApproved' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const VerificationRequest = IDL.Record({
  'id' : VerificationRequestId,
  'status' : VerificationStatus,
  'requester' : IDL.Principal,
  'submittedAt' : Time,
  'reviewComment' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(Time),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'amount' : BitcoinAmount,
  'transactionId' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'REJECTED' : IDL.Null,
  'PAID' : IDL.Null,
  'PENDING' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : WithdrawalRequestId,
  'status' : WithdrawalStatus,
  'method' : IDL.Text,
  'failureReason' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'account' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'amount' : BitcoinAmount,
});
export const BitcoinPurchaseRecord = IDL.Record({
  'amount' : BitcoinAmount,
  'verifiedAt' : Time,
  'verifiedBy' : IDL.Principal,
  'transactionId' : IDL.Text,
});
export const BlockchainApiEndpoint = IDL.Record({
  'fee' : IDL.Opt(IDL.Nat),
  'url' : IDL.Text,
  'supportsBroadcast' : IDL.Bool,
  'provider' : IDL.Text,
  'apiKey' : IDL.Opt(IDL.Text),
});
export const AdminConfig = IDL.Record({
  'endpoints' : IDL.Vec(BlockchainApiEndpoint),
  'maxRetries' : IDL.Nat,
  'preferredOrder' : IDL.Vec(IDL.Text),
});
export const BitcoinAddress = IDL.Record({
  'creator' : IDL.Principal,
  'publicKey' : IDL.Vec(IDL.Nat8),
  'createdAt' : Time,
  'network' : IDL.Variant({ 'mainnet' : IDL.Null, 'testnet' : IDL.Null }),
  'address' : IDL.Text,
  'addressType' : IDL.Variant({ 'P2WPKH' : IDL.Null }),
  'segwitMetadata' : SegwitMetadata,
});
export const PeerTransferId = IDL.Nat;
export const PeerTransferStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PeerTransferRequest = IDL.Record({
  'id' : PeerTransferId,
  'status' : PeerTransferStatus,
  'deleted' : IDL.Bool,
  'createdAt' : Time,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'lastUpdated' : Time,
  'recipient' : IDL.Principal,
  'approvalTimestamp' : IDL.Opt(Time),
  'sender' : IDL.Principal,
  'approver' : IDL.Opt(IDL.Principal),
  'rejectionTimestamp' : IDL.Opt(Time),
  'amount' : BitcoinAmount,
});
export const ReserveMultisigConfig = IDL.Record({
  'threshold' : IDL.Nat,
  'redeemScript' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'pubkeys' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const TransactionType = IDL.Variant({
  'adjustment' : IDL.Null,
  'withdrawalRejected' : IDL.Null,
  'withdrawalPaid' : IDL.Null,
  'withdrawalRequested' : IDL.Null,
  'creditPurchase' : IDL.Null,
  'debit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : BitcoinAmount,
});
export const BitcoinPurchaseRecordInput = IDL.Record({
  'amount' : BitcoinAmount,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveVerificationRequest' : IDL.Func(
      [VerificationRequestId, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'approveWithdrawal' : IDL.Func([WithdrawalRequestId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBitcoinAddress' : IDL.Func(
      [
        IDL.Variant({ 'P2WPKH' : IDL.Null }),
        IDL.Variant({ 'mainnet' : IDL.Null, 'testnet' : IDL.Null }),
      ],
      [IDL.Text],
      [],
    ),
  'creditBtcWithVerification' : IDL.Func(
      [IDL.Principal, IDL.Text, BitcoinAmount],
      [],
      [],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getBitcoinPurchase' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BitcoinPurchaseRecord)],
      ['query'],
    ),
  'getBitcoinPurchases' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, BitcoinPurchaseRecord))],
      ['query'],
    ),
  'getBlockchainApiConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
  'getCallerBalance' : IDL.Func([], [BitcoinAmount], ['query']),
  'getCallerBitcoinAddress' : IDL.Func(
      [],
      [IDL.Opt(BitcoinAddress)],
      ['query'],
    ),
  'getCallerPeerTransfers' : IDL.Func(
      [],
      [IDL.Vec(PeerTransferRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'getCallerWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getPeerTransfer' : IDL.Func(
      [PeerTransferId],
      [IDL.Opt(PeerTransferRequest)],
      ['query'],
    ),
  'getReserveMultisigConfig' : IDL.Func(
      [],
      [IDL.Opt(ReserveMultisigConfig)],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserBitcoinAddress' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BitcoinAddress)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerificationRequest' : IDL.Func(
      [VerificationRequestId],
      [IDL.Opt(VerificationRequest)],
      ['query'],
    ),
  'getWithdrawalRequest' : IDL.Func(
      [WithdrawalRequestId],
      [IDL.Opt(WithdrawalRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWithdrawalAsPaid' : IDL.Func([WithdrawalRequestId], [], []),
  'recordBitcoinPurchase' : IDL.Func(
      [BitcoinPurchaseRecordInput],
      [VerificationRequestId],
      [],
    ),
  'rejectVerificationRequest' : IDL.Func(
      [VerificationRequestId, IDL.Text],
      [],
      [],
    ),
  'rejectWithdrawal' : IDL.Func([WithdrawalRequestId, IDL.Text], [], []),
  'requestWithdrawal' : IDL.Func(
      [BitcoinAmount, IDL.Text, IDL.Opt(IDL.Text)],
      [WithdrawalRequestId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendCreditsToPeer' : IDL.Func(
      [IDL.Principal, BitcoinAmount],
      [PeerTransferId],
      [],
    ),
  'setBlockchainApiConfig' : IDL.Func([AdminConfig], [], []),
  'setReserveMultisigConfig' : IDL.Func([ReserveMultisigConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VerificationRequestId = IDL.Nat;
  const WithdrawalRequestId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BitcoinAmount = IDL.Nat;
  const SegwitMetadata = IDL.Record({ 'p2wpkhStatus' : IDL.Bool });
  const BitcoinWallet = IDL.Record({
    'publicKey' : IDL.Vec(IDL.Nat8),
    'address' : IDL.Text,
    'segwitMetadata' : SegwitMetadata,
  });
  const UserProfile = IDL.Record({
    'bitcoinWallet' : IDL.Opt(BitcoinWallet),
    'name' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'instantApproved' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const VerificationRequest = IDL.Record({
    'id' : VerificationRequestId,
    'status' : VerificationStatus,
    'requester' : IDL.Principal,
    'submittedAt' : Time,
    'reviewComment' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(Time),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'amount' : BitcoinAmount,
    'transactionId' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'REJECTED' : IDL.Null,
    'PAID' : IDL.Null,
    'PENDING' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : WithdrawalRequestId,
    'status' : WithdrawalStatus,
    'method' : IDL.Text,
    'failureReason' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'account' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'amount' : BitcoinAmount,
  });
  const BitcoinPurchaseRecord = IDL.Record({
    'amount' : BitcoinAmount,
    'verifiedAt' : Time,
    'verifiedBy' : IDL.Principal,
    'transactionId' : IDL.Text,
  });
  const BlockchainApiEndpoint = IDL.Record({
    'fee' : IDL.Opt(IDL.Nat),
    'url' : IDL.Text,
    'supportsBroadcast' : IDL.Bool,
    'provider' : IDL.Text,
    'apiKey' : IDL.Opt(IDL.Text),
  });
  const AdminConfig = IDL.Record({
    'endpoints' : IDL.Vec(BlockchainApiEndpoint),
    'maxRetries' : IDL.Nat,
    'preferredOrder' : IDL.Vec(IDL.Text),
  });
  const BitcoinAddress = IDL.Record({
    'creator' : IDL.Principal,
    'publicKey' : IDL.Vec(IDL.Nat8),
    'createdAt' : Time,
    'network' : IDL.Variant({ 'mainnet' : IDL.Null, 'testnet' : IDL.Null }),
    'address' : IDL.Text,
    'addressType' : IDL.Variant({ 'P2WPKH' : IDL.Null }),
    'segwitMetadata' : SegwitMetadata,
  });
  const PeerTransferId = IDL.Nat;
  const PeerTransferStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PeerTransferRequest = IDL.Record({
    'id' : PeerTransferId,
    'status' : PeerTransferStatus,
    'deleted' : IDL.Bool,
    'createdAt' : Time,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'lastUpdated' : Time,
    'recipient' : IDL.Principal,
    'approvalTimestamp' : IDL.Opt(Time),
    'sender' : IDL.Principal,
    'approver' : IDL.Opt(IDL.Principal),
    'rejectionTimestamp' : IDL.Opt(Time),
    'amount' : BitcoinAmount,
  });
  const ReserveMultisigConfig = IDL.Record({
    'threshold' : IDL.Nat,
    'redeemScript' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'pubkeys' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const TransactionType = IDL.Variant({
    'adjustment' : IDL.Null,
    'withdrawalRejected' : IDL.Null,
    'withdrawalPaid' : IDL.Null,
    'withdrawalRequested' : IDL.Null,
    'creditPurchase' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : BitcoinAmount,
  });
  const BitcoinPurchaseRecordInput = IDL.Record({
    'amount' : BitcoinAmount,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveVerificationRequest' : IDL.Func(
        [VerificationRequestId, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'approveWithdrawal' : IDL.Func([WithdrawalRequestId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBitcoinAddress' : IDL.Func(
        [
          IDL.Variant({ 'P2WPKH' : IDL.Null }),
          IDL.Variant({ 'mainnet' : IDL.Null, 'testnet' : IDL.Null }),
        ],
        [IDL.Text],
        [],
      ),
    'creditBtcWithVerification' : IDL.Func(
        [IDL.Principal, IDL.Text, BitcoinAmount],
        [],
        [],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getBitcoinPurchase' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BitcoinPurchaseRecord)],
        ['query'],
      ),
    'getBitcoinPurchases' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, BitcoinPurchaseRecord))],
        ['query'],
      ),
    'getBlockchainApiConfig' : IDL.Func([], [IDL.Opt(AdminConfig)], ['query']),
    'getCallerBalance' : IDL.Func([], [BitcoinAmount], ['query']),
    'getCallerBitcoinAddress' : IDL.Func(
        [],
        [IDL.Opt(BitcoinAddress)],
        ['query'],
      ),
    'getCallerPeerTransfers' : IDL.Func(
        [],
        [IDL.Vec(PeerTransferRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'getCallerWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getPeerTransfer' : IDL.Func(
        [PeerTransferId],
        [IDL.Opt(PeerTransferRequest)],
        ['query'],
      ),
    'getReserveMultisigConfig' : IDL.Func(
        [],
        [IDL.Opt(ReserveMultisigConfig)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserBitcoinAddress' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BitcoinAddress)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerificationRequest' : IDL.Func(
        [VerificationRequestId],
        [IDL.Opt(VerificationRequest)],
        ['query'],
      ),
    'getWithdrawalRequest' : IDL.Func(
        [WithdrawalRequestId],
        [IDL.Opt(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWithdrawalAsPaid' : IDL.Func([WithdrawalRequestId], [], []),
    'recordBitcoinPurchase' : IDL.Func(
        [BitcoinPurchaseRecordInput],
        [VerificationRequestId],
        [],
      ),
    'rejectVerificationRequest' : IDL.Func(
        [VerificationRequestId, IDL.Text],
        [],
        [],
      ),
    'rejectWithdrawal' : IDL.Func([WithdrawalRequestId, IDL.Text], [], []),
    'requestWithdrawal' : IDL.Func(
        [BitcoinAmount, IDL.Text, IDL.Opt(IDL.Text)],
        [WithdrawalRequestId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendCreditsToPeer' : IDL.Func(
        [IDL.Principal, BitcoinAmount],
        [PeerTransferId],
        [],
      ),
    'setBlockchainApiConfig' : IDL.Func([AdminConfig], [], []),
    'setReserveMultisigConfig' : IDL.Func([ReserveMultisigConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };