/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BitcoinAmount = bigint;
export interface BitcoinWallet {
  'publicKey' : Uint8Array,
  'address' : string,
  'segwitMetadata' : SegwitMetadata,
}
export interface SegwitMetadata { 'p2wpkhStatus' : boolean }
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'transactionType' : TransactionType,
  'user' : Principal,
  'timestamp' : Time,
  'amount' : BitcoinAmount,
}
export type TransactionType = { 'adjustment' : null } |
  { 'withdrawalRejected' : null } |
  { 'withdrawalPaid' : null } |
  { 'withdrawalRequested' : null } |
  { 'creditPurchase' : null } |
  { 'debit' : null };
export interface UserProfile {
  'bitcoinWallet' : [] | [BitcoinWallet],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];