/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionType = IDL.Variant({
  'adjustment' : IDL.Null,
  'creditPurchase' : IDL.Null,
  'debit' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const TransferStatus = IDL.Variant({
  'COMPLETED' : IDL.Null,
  'VERIFIED' : IDL.Null,
  'IN_PROGRESS' : IDL.Null,
  'FAILED' : IDL.Null,
});
export const SendBTCRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransferStatus,
  'owner' : IDL.Principal,
  'destinationAddress' : IDL.Text,
  'totalCost' : IDL.Nat,
  'networkFee' : IDL.Nat,
  'timestamp' : Time,
  'blockchainTxId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustCredits' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignInitialAdminCredits' : IDL.Func([], [], []),
  'getCallerBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEstimatedNetworkFee' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransferRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SendBTCRequest)],
      ['query'],
    ),
  'getTransferStatus' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TransferStatus)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerificationEndpoint' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeTestOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
  'purchaseCredits' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendBTC' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'transferCreditsToUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'verifyBTCTransfer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionType = IDL.Variant({
    'adjustment' : IDL.Null,
    'creditPurchase' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const TransferStatus = IDL.Variant({
    'COMPLETED' : IDL.Null,
    'VERIFIED' : IDL.Null,
    'IN_PROGRESS' : IDL.Null,
    'FAILED' : IDL.Null,
  });
  const SendBTCRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransferStatus,
    'owner' : IDL.Principal,
    'destinationAddress' : IDL.Text,
    'totalCost' : IDL.Nat,
    'networkFee' : IDL.Nat,
    'timestamp' : Time,
    'blockchainTxId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustCredits' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignInitialAdminCredits' : IDL.Func([], [], []),
    'getCallerBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEstimatedNetworkFee' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransferRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SendBTCRequest)],
        ['query'],
      ),
    'getTransferStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TransferStatus)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerificationEndpoint' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeTestOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
    'purchaseCredits' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendBTC' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'transferCreditsToUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'verifyBTCTransfer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };